[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[groups.cloudflare-blocklist]
type = "blocklist"
resolvers = ["cloudflare-dot"]
format    = "domain"
blocklist = [
  'evil.com',
  '.facebook.com',
  '*.twitter.com',
]
allowlist-format = "domain"
allowlist = [                # Allowlist items override/bypass blocklist items
  'allowed.facebook.com',
]

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "cloudflare-blocklist"

[listeners.local-tcp]
address = ":53"
protocol = "tcp"
resolver = "cloudflare-blocklist"
