[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[groups.cloudflare-blocklist]
type = "blocklist"
resolvers = ["cloudflare-dot"] # Anything that passes the filter is sent on to this resolver
format    = "regexp"           # "domain", "hosts" or "regexp", defaults to "regexp"
blocklist = [                  # Define the names to be blocked
    '(^|\.)evil\.com\.$',
    '(^|\.)malicious[123]\.com\.$',
]

[listeners.local-udp]
address = ":1153"
protocol = "udp"
resolver = "cloudflare-blocklist"

[listeners.local-tcp]
address = ":1153"
protocol = "tcp"
resolver = "cloudflare-blocklist"
