[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[groups.cloudflare-blocklist]
type      = "blocklist-v2"
resolvers = ["cloudflare-dot"]
blocklist-refresh = 86400 # Time to refresh the blocklist(s) in seconds
blocklist-source = [
   {format = "domain", source = "./example-config/domains.txt"}, # Type and location of the local blocklist file.
]

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "cloudflare-blocklist"

[listeners.local-tcp]
address = ":53"
protocol = "tcp"
resolver = "cloudflare-blocklist"
