# Cache backed by Redis database

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-dot"]
cache-negative-ttl = 10         # Optional, TTL to apply to responses without a SOA
cache-answer-shuffle = "round-robin" # Optional, rotate the order of cached responses
backend = {type = "redis", redis-address = "127.0.0.1:6379" }

[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "cloudflare-cached"
