# Cache that sets an upper bound on the TTL of NXDOMAIN even if they have a SOA.

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-dot"]
cache-rcode-max-ttl = { 3 = 60 } # NXDOMAIN records should not be cached for more than a minute

[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "cloudflare-cached"
