# Filters client IPs based on geo location. Matching clients from
# those locations will receive a REFUSED response.

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "cloudflare-blocklist"

[groups.cloudflare-blocklist]
type                = "client-blocklist"
resolvers           = ["cloudflare-dot"]
blocklist-resolver  = "static-refused" # Any match is sent to a static responder
blocklist-format    = "location"
blocklist           = [
  "6255148", # Europe
  "2017370", # Russia
]

[groups.static-refused]
type  = "static-responder"
rcode = 5 # REFUSED

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"
