# Server-side of a simple DNS-over-DTLS proxy.

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[listeners.local-dtls]
address = ":3853"
protocol = "dtls"
resolver = "cloudflare-dot"
server-crt = "/home/folbrich/workspace/routedns/testdata/server.crt"
server-key = "/home/folbrich/workspace/routedns/testdata/server.key"
