[resolvers.google-dot]
address = "8.8.8.8:853"
protocol = "dot"

[groups.google-ecs]
type = "ecs-modifier"
resolvers = ["google-dot"]
ecs-op = "privacy"
ecs-prefix4 = 16
ecs-prefix6 = 64

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "google-ecs"

[listeners.local-tcp]
address = ":53"
protocol = "tcp"
resolver = "google-ecs"
