# This is the client-half of a fully secure DoT configuration where the
# server is private and expects the client to present a cert by a CA it
# trusts.
title = "RouteDNS configuration"

[resolvers]

  [resolvers.myserver-dot]
  address = "<IP>:853"
  protocol = "dot"
  ca = "/path/to/ca.crt"
  client-crt = "/path/to/client.crt"
  client-key = "/path/to/client.crt"

[listeners]

  [listeners.local]
  address = ":53"
  protocol = "udp"
  resolver = "myserver-dot"
