# Simple proxy using a cache.

[resolvers.cloudflare-dot]
address = "1.1.1.1:53"
protocol = "udp"



[groups.cloudflare-cached-with-prefetch]
type = "cache"
resolvers = ["cloudflare-dot"]
cache-size = 100               # Optional, max number of responses to cache. Default unlimited
cache-negative-ttl = 10         # Optional, TTL to apply to responses without a SOA
cache-answer-shuffle = "round-robin" # Optional, rotate the order of cached responses

[groups.cache-prefetch]
type = "cache-prefetch"
cache-ttl-polling-check-interval = 1 # Prefetching interval
record-query-hits-min = 1 # number of querys before a preload job is made
resolvers = [ "cloudflare-cached-with-prefetch" ] # This should always be after a cache

[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "cache-prefetch"
