# This config could be used when DNS-over-TLS is desirable, but insecure DNS servers
# are needed to resolve certain domains. A common use case when using split VPN into
# one's company network. Company resources can only be resolved using company DNS
# servers, while everything else can be sent securely over TLS.

title = "RouteDNS configuration for split DNS"

[resolvers]

  [resolvers.cloudflare-dot]
  address = "1.1.1.1:853"
  protocol = "dot"

  [resolvers.mycompany-dns]
  address = "10.0.0.1:53"
  protocol = "udp"

[routers]

  [routers.router1]

    # Send everything for '*.mycomany.com.' to the company's DNS, possibly through a VPN tunnel
    [[routers.router1.routes]]
    name = '\.mycompany\.com\.$'
    resolver="mycompany-dns"
 
    # Everything else can go securely to CloudFlare
    [[routers.router1.routes]]
    resolver="cloudflare-dot"

[listeners]

  [listeners.local-udp]
  address = "127.0.0.1:53"
  protocol = "udp"
  resolver = "router1"

  [listeners.local-tcp]
  address = "127.0.0.1:53"
  protocol = "tcp"
  resolver = "router1"
